# Create a Four-Factor Model
# The WAIS-III IQ scale has a proposed four-factor model structure with verbal comprehension, working memory, perceptual organization, and # processing speed. You should analyze this structure to determine if the model fits the data and that there are no problems with the  
# model. In this exercise, you should find a Heywood case that indicates potential problems with the model.

# Build a four-factor model
wais.model <- 'verbalcomp =~ vocab + simil + inform + compreh 
workingmemory =~ arith + digspan + lnseq
perceptorg =~ piccomp + block + matrixreason
processing =~ digsym + symbolsearch'

# Analyze the model and include the data argument
wais.fit <- cfa(model= wais.model, data=IQdata)

# Summarize the model with fit.measures and standardized loadings
summary(wais.fit, fit.measures=TRUE, standardized=TRUE)

# Edit the original model
wais.model <- 'verbalcomp =~ vocab + simil + inform + compreh 
workingmemory =~ arith + digspan + lnseq
performance =~ piccomp + block + matrixreason + digsym + symbolsearch'

# Analyze the model and include the data argument
wais.fit <- cfa(model = wais.model, data = IQdata)

# Summarize the model
summary(wais.fit, standardized = TRUE, fit.measures = TRUE)

# Load the library
library(semPlot)

# Update the default picture
semPaths(object = wais.fit,
         layout = "tree",
         rotation = 1,
         whatLabels = "std",
         edge.label.cex = 1,
         what = "std",
         edge.color = "black")
        
# Add Paths to Improve Fit
# Examine modification indices 
modificationindices(wais.fit, sort = TRUE)

# Update the three-factor model
wais.model2 <- 'verbalcomp =~ vocab + simil + inform + compreh 
workingmemory =~ arith + digspan + lnseq
perceptorg =~ piccomp + block + matrixreason + digsym + symbolsearch
simil ~~ inform'

# Analyze the three-factor model where data is IQdata
wais.fit2 <- cfa(model = wais.model2, data = IQdata)
summary(wais.fit2, fit.measures= TRUE, standardized=TRUE)

# Compare the models
anova(wais.fit, wais.fit2)

# View the fit indices for the original model
fitmeasures(wais.fit, c("aic", "ecvi"))

# View the fit indices for the updated model
fitmeasures(wais.fit2, c("aic", "ecvi"))

# Create a Hierarchical Model
# The underlying theory about intelligence states that a general IQ factor predicts performance on the verbal comprehension, working 
# memory, and perceptual organization subfactors. Therefore, you should create a hierarchical model that demonstrates that relationship # between the second order latent variable and the first layer of latent variables.

# Update the three-factor model to a hierarchical model
wais.model3 <- 'verbalcomp =~ vocab + simil + inform + compreh 
workingmemory =~ arith + digspan + lnseq
perceptorg =~ piccomp + block + matrixreason + digsym + symbolsearch
simil ~~ inform
general =~ verbalcomp + workingmemory + perceptorg'

# Analyze the hierarchical model where data is IQdata
wais.fit3 <- cfa(model = wais.model3, data = IQdata)

# Examine the fit indices for the old model
fitmeasures(wais.fit2, c("rmsea", "srmr"))

# Examine the fit indices for the new model
fitmeasures(wais.fit3, c("rmsea","srmr"))

# Load the library
library(semPlot)

# Update the default picture
semPaths(object = wais.fit3,
         layout = "tree",
         rotation = 1,
         whatLabels = "std",
         edge.label.cex = 1,
         what = "std",
         edge.color = "navy")
